/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.base.Strings;


/**
 *
 * To start the application:
 * ./gradlew build
 * java -jar ./HW01-gradle/build/libs/gradleHelloWorld-0.1.jar [args ..]
 *
 */
public class HelloOtus {
    public static void main(String... args) {
        System.out.println(Strings.lenientFormat("%s, Hello from guava", args));
    }
}
